[build]
  functions = "functions"  # Where your serverless functions are stored

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"  # Routes API requests to the serverless function
  status = 200
